Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          Carbon:
            TailwindColors:
              backgroundAndForeground:
                type: array
                ui:
                  inspector:
                    editor: 'Carbon.TailwindColors/BackgroundAndForeground'
                    editorOptions:
                      minimalStrenghtSpan: 650
              groups:
                type: string
                ui:
                  inspector:
                    editor: 'Carbon.TailwindColors/Groups'
              colors:
                type: array
                ui:
                  inspector:
                    editor: 'Carbon.TailwindColors/Colors'
                    editorOptions:
                      placeholder: null
